item {
  id: 1
  name: 'monster'
}

item {
  id: 2
  name: 'fusion_monster'
}

item {
  id: 3
  name: 'link_monster'
}

item {
  id: 4
  name: 'pendulum_monster'
}

item {
  id: 5
  name: 'ritual_monster'
}

item {
  id: 6
  name: 'spell'
}

item {
  id: 7
  name: 'synchro_monster'
}

item {
  id: 8
  name: 'trap'
}

item {
  id: 9
  name: 'xyz_monster'
}
  