item {
  id: 1
  name: 'monster'
}

item {
  id: 2
  name: 'spell_link_ritual'
}

item {
  id: 3
  name: 'trap_fusion'
}

item {
  id: 4
  name: 'synchro_monster'
}

item {
  id: 5
  name: 'xyz_monster'
}
